In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from math import ceil
from scipy import stats

In [29]:
filename = ("US-Ne1", "US-Ne2", "US-Ne3", "US-Var")

compare_vars = ["geeSEBAL", "PT-JPL", "SSEBop", "SIMS", "eeMETRIC", "DisALEXI", "Ensemble", "SIF_ET", "Climatology"]


for fn in filename:
    df = pd.read_csv(fn+"_clim.csv", delimiter = ',', parse_dates=["Date"])
    df["Date"] = pd.to_datetime(df["Date"])
    df.set_index("Date", inplace=True)
    season_filters = {
        "All Months": df,
        "DJF": df[df.index.month.isin([12, 1, 2])],
        "MAM": df[df.index.month.isin([3, 4, 5])],
        "JJA": df[df.index.month.isin([6, 7, 8])],
        "SON": df[df.index.month.isin([9, 10, 11])],
        }
    season_names = list(season_filters.keys())
    results = []


    for row_idx, season_name in enumerate(season_names):
        season_df = season_filters[season_name]

        for col_idx, var in enumerate(compare_vars):
            subset = season_df[["observed_ET", var]].dropna()
            if subset.empty:
                continue

            y = subset[var].values.reshape(-1, 1)
            obs = subset["observed_ET"].values

            model = LinearRegression().fit(y, obs)
            y_pred = model.predict(y)
            r2 = r2_score(obs, y_pred)
            
            y = y.reshape(-1, )
            y_pred = y_pred.reshape(-1, )
            
            RMSE = np.sqrt(mean_squared_error(obs, y))
            MAE = mean_absolute_error(obs, y)
            MBE = (sum(y-obs))/len(obs)
            SRMSE = RMSE/(np.std(obs))

            results.append({
                "Season": season_name,
                "Variable": var,
                "R2": round(r2, 3),
                "RMSE": round(RMSE, 3),
                "MAE": round(MAE,3),
                "MBE": round(MBE,3),
                "# Months": len(subset),
                "# Years": len(subset.index.to_period("Y").unique())
            })
            season_r2_dict[var] = round(r2, 3)
            season_RMSE_dict[var] = round(RMSE, 3)

    results_df = pd.DataFrame(results)
    display(results_df)
    results_df.to_csv(fn+'_stats.csv')

        Season     Variable     R2    RMSE     MAE     MBE  # Months  # Years
0   All Months     geeSEBAL  0.869  25.734  19.131 -12.123       203       19
1   All Months       PT-JPL  0.893  23.851  16.917  -9.879       203       19
2   All Months       SSEBop  0.880  24.971  19.821  -9.988       203       19
3   All Months         SIMS  0.875  22.242  17.152   2.106       203       19
4   All Months     eeMETRIC  0.837  27.071  21.198  -5.964       203       19
5   All Months     DisALEXI  0.916  19.942  14.685  -7.184       203       19
6   All Months     Ensemble  0.923  19.546  15.142  -8.868       203       19
7   All Months       SIF_ET  0.878  31.130  21.373 -11.272       223       19
8   All Months  Climatology  0.944  14.658  10.314   0.000       223       19
9          DJF     geeSEBAL  0.105  11.957   9.821  -7.837        48       19
10         DJF       PT-JPL  0.208  10.054   8.245  -7.010        48       19
11         DJF       SSEBop  0.000  13.933  11.637 -10.797        48       19
12         DJF         SIMS  0.172   9.405   7.001  -5.256        48       19
13         DJF     eeMETRIC  0.005  13.307  10.833  -9.214        48       19
14         DJF     DisALEXI  0.281   8.475   7.052  -2.556        48       19
15         DJF     Ensemble  0.222  10.787   8.629  -8.270        48       19
16         DJF       SIF_ET  0.004  12.639  11.496   9.939        55       19
17         DJF  Climatology  0.327   6.230   4.990  -0.000        55       19
18         MAM     geeSEBAL  0.297  28.690  23.576 -12.334        49       17
19         MAM       PT-JPL  0.507  15.954  12.217  -5.516        49       17
20         MAM       SSEBop  0.484  32.453  29.625 -28.334        49       17
21         MAM         SIMS  0.675  22.751  18.775  10.790        49       17
22         MAM     eeMETRIC  0.313  31.504  27.278 -24.314        49       17
23         MAM     DisALEXI  0.539  22.010  18.695 -17.697        49       17
24         MAM     Ensemble  0.599  20.834  18.140 -16.150        49       17
25         MAM       SIF_ET  0.498  17.776  14.134 -10.238        54       18
26         MAM  Climatology  0.559  13.602  10.646   0.000        54       18
27         JJA     geeSEBAL  0.561  36.760  30.043 -25.405        52       19
28         JJA       PT-JPL  0.424  40.397  34.784 -29.426        52       19
29         JJA       SSEBop  0.657  28.614  23.196  -9.959        52       19
30         JJA         SIMS  0.389  30.442  26.529  -9.424        52       19
31         JJA     eeMETRIC  0.580  30.150  23.738 -11.147        52       19
32         JJA     DisALEXI  0.612  27.974  20.330  -5.613        52       19
33         JJA     Ensemble  0.687  26.734  21.606 -16.626        52       19
34         JJA       SIF_ET  0.205  55.535  46.499 -45.552        57       19
35         JJA  Climatology  0.624  21.641  16.751  -0.000        57       19
36         SON     geeSEBAL  0.720  17.729  12.867  -2.951        54       19
37         SON       PT-JPL  0.775  15.694  11.685   2.437        54       19
38         SON       SSEBop  0.727  20.675  14.949   7.351        54       19
39         SON         SIMS  0.775  20.472  15.672  11.872        54       19
40         SON     eeMETRIC  0.714  28.663  22.451  18.568        54       19
41         SON     DisALEXI  0.785  15.426  12.396  -3.273        54       19
42         SON     Ensemble  0.800  15.833  11.985   4.679        54       19
43         SON       SIF_ET  0.827  15.930  12.634   1.560        57       19
44         SON  Climatology  0.847  12.629   8.698   0.000        57       19

        Season     Variable     R2    RMSE     MAE     MBE  # Months  # Years
0   All Months     geeSEBAL  0.874  25.580  19.091 -14.048       202       19
1   All Months       PT-JPL  0.895  21.801  14.237  -7.438       202       19
2   All Months       SSEBop  0.875  25.167  20.488 -10.519       202       19
3   All Months         SIMS  0.861  23.197  17.878   5.555       202       19
4   All Months     eeMETRIC  0.831  27.853  21.763  -8.261       202       19
5   All Months     DisALEXI  0.924  19.897  15.208 -10.020       202       19
6   All Months     Ensemble  0.922  19.279  15.061  -9.517       202       19
7   All Months       SIF_ET  0.869  27.597  18.643  -5.500       223       19
8   All Months  Climatology  0.929  15.842   9.966   0.000       223       19
9          DJF     geeSEBAL  0.061  11.406   8.983  -7.136        46       18
10         DJF       PT-JPL  0.081   9.284   7.096  -5.630        46       18
11         DJF       SSEBop  0.025  13.438  11.143 -10.367        46       18
12         DJF         SIMS  0.288   7.592   5.609  -4.289        46       18
13         DJF     eeMETRIC  0.005  12.001   9.668  -8.913        46       18
14         DJF     DisALEXI  0.046  10.361   8.145  -5.197        46       18
15         DJF     Ensemble  0.140  10.187   8.015  -7.934        46       18
16         DJF       SIF_ET  0.047  13.632  12.570  11.727        55       19
17         DJF  Climatology  0.359   5.213   3.823  -0.000        55       19
18         MAM     geeSEBAL  0.431  29.437  25.093 -14.823        49       17
19         MAM       PT-JPL  0.660  11.982   9.658  -1.721        49       17
20         MAM       SSEBop  0.587  29.498  26.895 -25.960        49       17
21         MAM         SIMS  0.727  25.089  22.000  16.434        49       17
22         MAM     eeMETRIC  0.306  33.817  29.982 -27.360        49       17
23         MAM     DisALEXI  0.519  22.332  19.246 -17.803        49       17
24         MAM     Ensemble  0.643  20.593  17.917 -16.189        49       17
25         MAM       SIF_ET  0.586  11.994   9.048  -2.640        54       18
26         MAM  Climatology  0.596  11.500   8.565   0.000        54       18
27         JJA     geeSEBAL  0.756  35.721  29.096 -27.155        53       19
28         JJA       PT-JPL  0.547  36.759  28.583 -24.144        53       19
29         JJA       SSEBop  0.740  29.087  24.041 -10.433        53       19
30         JJA         SIMS  0.461  30.808  26.418  -3.802        53       19
31         JJA     eeMETRIC  0.682  30.946  25.090 -11.472        53       19
32         JJA     DisALEXI  0.812  23.961  17.297  -8.382        53       19
33         JJA     Ensemble  0.795  25.413  20.333 -16.176        53       19
34         JJA       SIF_ET  0.224  48.667  38.716 -33.723        57       19
35         JJA  Climatology  0.568  26.180  20.193  -0.000        57       19
36         SON     geeSEBAL  0.778  17.267  12.434  -6.369        54       19
37         SON       PT-JPL  0.785  15.751  10.393   2.231        54       19
38         SON       SSEBop  0.651  24.402  19.148   3.278        54       19
39         SON         SIMS  0.787  21.472  16.208  13.253        54       19
40         SON     eeMETRIC  0.702  28.314  21.342  12.778        54       19
41         SON     DisALEXI  0.748  19.326  15.510  -8.672        54       19
42         SON     Ensemble  0.781  16.830  13.296   1.726        54       19
43         SON       SIF_ET  0.826  17.190  13.521   3.389        57       19
44         SON  Climatology  0.871  12.042   6.994   0.000        57       19

        Season     Variable     R2    RMSE     MAE     MBE  # Months  # Years
0   All Months     geeSEBAL  0.855  22.115  16.636  -8.946       197       18
1   All Months       PT-JPL  0.887  17.930  12.642  -0.469       197       18
2   All Months       SSEBop  0.886  21.212  16.839  -6.783       197       18
3   All Months         SIMS  0.854  25.145  18.889  12.851       197       18
4   All Months     eeMETRIC  0.837  24.103  18.242  -2.913       197       18
5   All Months     DisALEXI  0.892  19.137  14.764  -4.016       197       18
6   All Months     Ensemble  0.917  16.015  12.222  -3.680       197       18
7   All Months       SIF_ET  0.871  20.396  15.779   2.881       222       19
8   All Months  Climatology  0.931  13.609   8.707   0.000       222       19
9          DJF     geeSEBAL  0.119   9.180   7.801  -5.362        46       17
10         DJF       PT-JPL  0.097   6.797   5.408  -2.530        46       17
11         DJF       SSEBop  0.016  10.278   8.693  -7.499        46       17
12         DJF         SIMS  0.185   6.192   4.586  -1.134        46       17
13         DJF     eeMETRIC  0.125   8.561   7.012  -6.325        46       17
14         DJF     DisALEXI  0.103   7.498   5.954  -1.697        46       17
15         DJF     Ensemble  0.209   6.818   5.344  -4.841        46       17
16         DJF       SIF_ET  0.085  14.769  13.644  13.497        55       19
17         DJF  Climatology  0.340   4.430   3.237  -0.000        55       19
18         MAM     geeSEBAL  0.201  25.036  21.064  -6.297        48       16
19         MAM       PT-JPL  0.617  12.396   9.130   3.662        48       16
20         MAM       SSEBop  0.465  23.754  21.755 -20.876        48       16
21         MAM         SIMS  0.735  29.395  25.216  21.526        48       16
22         MAM     eeMETRIC  0.090  27.382  23.747 -17.330        48       16
23         MAM     DisALEXI  0.138  20.716  16.898  -8.484        48       16
24         MAM     Ensemble  0.361  16.753  14.302  -8.867        48       16
25         MAM       SIF_ET  0.405  13.067   9.065  -0.627        54       18
26         MAM  Climatology  0.437  12.333   8.254  -0.000        54       18
27         JJA     geeSEBAL  0.670  30.444  25.318 -21.225        52       18
28         JJA       PT-JPL  0.441  27.624  22.321 -10.205        52       18
29         JJA       SSEBop  0.689  24.502  19.097  -1.871        52       18
30         JJA         SIMS  0.317  31.441  24.767  12.114        52       18
31         JJA     eeMETRIC  0.599  27.742  22.034  -1.563        52       18
32         JJA     DisALEXI  0.667  24.885  20.558  -0.255        52       18
33         JJA     Ensemble  0.716  20.158  16.338  -5.338        52       18
34         JJA       SIF_ET  0.343  30.933  24.554 -13.282        56       19
35         JJA  Climatology  0.629  20.808  15.600   0.000        56       19
36         SON     geeSEBAL  0.706  16.681  11.587  -2.151        51       18
37         SON       PT-JPL  0.767  16.658  12.603   7.429        51       18
38         SON       SSEBop  0.647  22.352  17.258   2.117        51       18
39         SON         SIMS  0.787  24.218  19.840  18.051        51       18
40         SON     eeMETRIC  0.690  26.222  19.325  12.358        51       18
41         SON     DisALEXI  0.707  18.128  14.796  -5.738        51       18
42         SON     Ensemble  0.767  16.442  12.272   3.941        51       18
43         SON       SIF_ET  0.808  17.546  15.578  11.841        57       19
44         SON  Climatology  0.844  11.531   7.644   0.000        57       19

        Season     Variable     R2    RMSE     MAE     MBE  # Months  # Years
0   All Months     geeSEBAL  0.208  43.858  30.882  25.096       200       18
1   All Months       PT-JPL  0.696  32.698  27.477  27.326       200       18
2   All Months       SSEBop  0.412  27.039  18.985  10.624       200       18
3   All Months     eeMETRIC  0.743  20.882  16.052  12.230       200       18
4   All Months     DisALEXI  0.378  28.662  19.891  11.443       200       18
5   All Months     Ensemble  0.522  26.855  19.317  14.817       200       18
6   All Months       SIF_ET  0.817  28.654  25.151  23.516       246       21
7   All Months  Climatology  0.908   8.871   5.123   0.000       246       21
8          DJF     geeSEBAL  0.321   8.204   6.366  -3.038        50       18
9          DJF       PT-JPL  0.574  15.691  14.507  14.484        50       18
10         DJF       SSEBop  0.520   8.864   7.397  -6.270        50       18
11         DJF     eeMETRIC  0.462   8.960   7.036  -1.450        50       18
12         DJF     DisALEXI  0.499   8.596   7.089  -5.500        50       18
13         DJF     Ensemble  0.601   6.386   4.818  -2.988        50       18
14         DJF       SIF_ET  0.638  22.177  21.589  21.589        60       21
15         DJF  Climatology  0.845   3.303   2.474   0.000        60       21
16         MAM     geeSEBAL  0.325  29.598  22.220   9.960        51       17
17         MAM       PT-JPL  0.120  37.496  28.257  27.691        51       17
18         MAM       SSEBop  0.475  17.420  14.225  -2.435        51       17
19         MAM     eeMETRIC  0.644  22.775  18.725  13.085        51       17
20         MAM     DisALEXI  0.394  19.534  15.653  -2.662        51       17
21         MAM     Ensemble  0.497  19.686  15.267   6.107        51       17
22         MAM       SIF_ET  0.598  11.542   8.063   1.678        63       21
23         MAM  Climatology  0.324  14.598  10.411   0.000        63       21
24         JJA     geeSEBAL  0.153  76.281  71.382  71.382        50       17
25         JJA       PT-JPL  0.791  44.614  43.476  43.476        50       17
26         JJA       SSEBop  0.076  47.761  42.812  42.812        50       17
27         JJA     eeMETRIC  0.279  30.982  27.774  27.686        50       17
28         JJA     DisALEXI  0.218  51.482  47.530  47.530        50       17
29         JJA     Ensemble  0.341  46.826  44.406  44.406        50       17
30         JJA       SIF_ET  0.597  41.046  40.293  40.293        63       21
31         JJA  Climatology  0.416   8.417   4.595   0.000        63       21
32         SON     geeSEBAL  0.342  30.546  23.587  22.330        49       17
33         SON       PT-JPL  0.251  24.864  23.573  23.573        49       17
34         SON       SSEBop  0.050  16.136  11.453   8.609        49       17
35         SON     eeMETRIC  0.011  13.362  10.510   9.528        49       17
36         SON     DisALEXI  0.008  13.267   9.163   6.591        49       17
37         SON     Ensemble  0.044  16.160  12.726  11.860        49       17
38         SON       SIF_ET  0.228  31.076  30.758  30.758        60       20
39         SON  Climatology  0.461   3.690   2.775  -0.000        60       20

In [30]:
site = ("US-Ne1", "US-Ne2", "US-Ne3", "US-Var")
plot_vars = ["ens_anom", "SIF_anom"]
results = []
for fn in site:
    df = pd.read_csv(fn+"_clim.csv", delimiter = ',', parse_dates=["Date"])
    df["Date"] = pd.to_datetime(df["Date"])
    df.set_index("Date", inplace=True)
    season_filters = {
        "All Months": df,
        "DJF": df[df.index.month.isin([12, 1, 2])],
        "MAM": df[df.index.month.isin([3, 4, 5])],
        "JJA": df[df.index.month.isin([6, 7, 8])],
        "SON": df[df.index.month.isin([9, 10, 11])],
        }
    season_names = list(season_filters.keys())
    for season_name in season_names:
        season_df = season_filters[season_name]
        for var in plot_vars:
            subset = season_df[["obs_anom", var]].dropna()
        
            y = subset[var].values.reshape(-1, 1)
            obs = subset["obs_anom"].values
            
            model = LinearRegression().fit(y, obs)
            y_pred = model.predict(y)
            r2 = r2_score(obs, y_pred)

            y = y.reshape(-1, )

            RMSE = np.sqrt(mean_squared_error(obs, y))
            MAE = mean_absolute_error(obs, y)
            MBE = (sum(y-obs))/len(obs)
            SRMSE = RMSE/(np.std(obs))
            
            results.append({
                "Site": fn,
                "Season": season_name,
                "Variable": var,
                "R2": round(r2, 3),
                "RMSE": round(RMSE, 3),
                "SRMSE": round(SRMSE, 3),
                "MAE": round(MAE,3),
                "MBE": '{:0.3e}'.format(MBE),
                "# Months": len(subset),
                "# Years": len(subset.index.to_period("Y").unique()),
            })
            
results_df = pd.DataFrame(results)
display(results_df)
results_df.to_csv('anom_stats.csv')

,Site,Season,Variable,R2,RMSE,SRMSE,MAE,MBE,# Months,# Years
0,US-Ne1,All Months,ens_anom,0.304,14.420,0.977,9.862,5.230e-01,203,19
1,US-Ne1,All Months,SIF_anom,0.003,17.081,1.165,11.868,4.040e-02,223,19
2,US-Ne1,DJF,ens_anom,0.167,5.839,0.931,4.605,3.717e-01,48,19
3,US-Ne1,DJF,SIF_anom,0.231,5.833,0.936,4.708,2.435e-02,55,19
4,US-Ne1,MAM,ens_anom,0.304,13.171,1.027,10.583,1.345e+00,49,17
5,US-Ne1,MAM,SIF_anom,0.002,14.468,1.064,11.912,1.414e-01,54,18
6,US-Ne1,JJA,ens_anom,0.367,20.692,0.923,14.200,-2.517e-01,52,19
7,US-Ne1,JJA,SIF_anom,0.045,27.676,1.279,21.622,1.379e-04,57,19
8,US-Ne1,SON,ens_anom,0.161,13.478,1.107,9.703,6.574e-01,54,19
9,US-Ne1,SON,SIF_anom,0.143,12.013,0.951,8.982,5.017e-04,57,19
10,US-Ne2,All Months,ens_anom,0.425,14.761,0.907,10.846,-5.922e-02,202,19
11,US-Ne2,All Months,SIF_anom,0.005,18.247,1.152,11.592,4.035e-02,223,19
12,US-Ne2,DJF,ens_anom,0.070,5.667,1.043,4.068,1.360e-01,46,18
13,US-Ne2,DJF,SIF_anom,0.056,5.074,0.973,3.702,2.438e-02,55,19
14,US-Ne2,MAM,ens_anom,0.372,12.692,1.099,9.837,2.521e-01,49,17
15,US-Ne2,MAM,SIF_anom,0.024,11.643,1.012,8.779,1.413e-01,54,18
16,US-Ne2,JJA,ens_anom,0.581,19.623,0.739,15.415,-6.128e-01,53,19
17,US-Ne2,JJA,SIF_anom,0.041,31.662,1.209,26.044,8.186e-05,57,19
18,US-Ne2,SON,ens_anom,0.073,16.237,1.316,13.051,3.532e-02,54,19
19,US-Ne2,SON,SIF_anom,0.092,12.122,1.007,7.418,3.551e-04,57,19
20,US-Ne3,All Months,ens_anom,0.100,14.566,1.251,10.605,2.897e-01,197,18
21,US-Ne3,All Months,SIF_anom,0.000,15.978,1.174,9.929,2.431e-02,222,19
22,US-Ne3,DJF,ens_anom,0.186,4.327,1.273,3.271,7.939e-01,46,17
23,US-Ne3,DJF,SIF_anom,0.048,4.322,0.976,3.196,1.598e-02,55,19
24,US-Ne3,MAM,ens_anom,0.058,14.109,1.891,11.419,2.182e+00,48,16
25,US-Ne3,MAM,SIF_anom,0.000,12.843,1.041,8.963,-9.858e-04,54,18
26,US-Ne3,JJA,ens_anom,0.211,19.285,1.098,15.448,-2.106e+00,52,18
27,US-Ne3,JJA,SIF_anom,0.002,26.058,1.252,19.615,8.154e-02,56,19
28,US-Ne3,SON,ens_anom,0.000,15.365,1.314,11.516,4.967e-01,51,18
29,US-Ne3,SON,SIF_anom,0.048,12.367,1.072,7.823,7.394e-05,57,19
30,US-Var,All Months,ens_anom,0.396,11.186,1.177,8.319,2.465e-01,200,18
31,US-Var,All Months,SIF_anom,0.406,6.875,0.775,4.367,1.937e-04,246,21
32,US-Var,DJF,ens_anom,0.064,5.548,1.617,4.232,3.424e-01,50,18
33,US-Var,DJF,SIF_anom,0.186,3.981,1.205,2.996,1.419e-04,60,21
34,US-Var,MAM,ens_anom,0.590,14.057,0.896,11.751,6.922e-01,51,17
35,US-Var,MAM,SIF_anom,0.489,10.597,0.726,7.747,1.483e-04,63,21
36,US-Var,JJA,ens_anom,0.188,14.711,1.610,11.452,5.001e-02,50,17
37,US-Var,JJA,SIF_anom,0.382,7.135,0.848,4.398,2.482e-04,63,21
38,US-Var,SON,ens_anom,0.066,7.267,1.900,5.720,-1.148e-01,49,17
39,US-Var,SON,SIF_anom,0.573,2.566,0.696,2.158,2.357e-04,60,20