In [3]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [61]:
fp = ("US-Ne1", "US-Ne2", "US-Ne3", "US-Var")
month_names = ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
comp_vars = ("SIF_ET", "Ensemble", "geeSEBAL", "PT-JPL", "SSEBop", "SIMS", "eeMETRIC", "DisALEXI", "Climatology")
results = []
month_occ = []
for fn in fp: 
    df = pd.read_csv(fn+"_clim.csv", delimiter = ',', parse_dates=["Date"])
    df["Date"] = pd.to_datetime(df["Date"])
    df.set_index("Date", inplace=True)
    for i, name in enumerate(month_names):
        month_df = df[df.index.month == i + 1]
        for var in comp_vars:
            subset = month_df[["observed_ET", var]].dropna()
            if subset.empty:
                continue

            y = subset[var].values.reshape(-1, 1)
            obs = subset["observed_ET"].values

            model = LinearRegression().fit(y, obs)
            y_pred = model.predict(y)
            r2 = r2_score(obs, y_pred)

            y = y.reshape(-1, )
            y_pred = y_pred.reshape(-1, )

            RMSE = np.sqrt(mean_squared_error(obs, y))
            MAE = mean_absolute_error(obs, y)
            MBE = (sum(y-obs))/len(obs)

            SRMSE = RMSE/(np.std(obs))

            results.append({
                "Site": fn,
                "month": name,
                "Variable": var,
                "R2": round(r2, 3),
                "RMSE": round(RMSE, 3),
                "SRMSE": round(SRMSE, 3),
                "MAE": round(MAE,3),
                "MBE": MBE
                })
        month_occ.append({
            "Site": fn, 
            "month": name,
            "# of occurrences": len(subset)
            })
            

vars = ["Ensemble", "SIF_ET", "Climatology",'eeMETRIC', 'geeSEBAL', 'DisALEXI', 'SSEBop', 'PT-JPL', 'SIMS']
results_df = pd.DataFrame(results)
month_occ = pd.DataFrame(month_occ)
display(results_df)
#results_df.to_csv("loc.csv")
#display(results_df.describe())

       Site month     Variable     R2    RMSE  SRMSE     MAE        MBE
0    US-Ne1   Jan       SIF_ET  0.206  13.812  3.374  13.269  13.268698
1    US-Ne1   Jan     Ensemble  0.294   6.839  1.751   5.906  -5.863729
2    US-Ne1   Jan     geeSEBAL  0.039   9.658  2.473   8.224  -5.588729
3    US-Ne1   Jan       PT-JPL  0.185   7.134  1.827   6.094  -4.569979
4    US-Ne1   Jan       SSEBop  0.004   9.601  2.459   8.443  -7.701229
..      ...   ...          ...    ...     ...    ...     ...        ...
415  US-Var   Dec       PT-JPL  0.001  16.497  6.274  15.423  15.423181
416  US-Var   Dec       SSEBop  0.025   7.121  2.708   5.974  -3.326819
417  US-Var   Dec     eeMETRIC  0.061   8.736  3.322   6.735  -0.820569
418  US-Var   Dec     DisALEXI  0.013   6.829  2.597   5.741  -5.483069
419  US-Var   Dec  Climatology  0.000   2.628  1.000   2.013   0.000276

[420 rows x 8 columns]

In [62]:
table = month_occ.pivot(index="Site", columns="month", values="# of occurrences")
table = table.reindex(month_names, axis=1)
display(table)

month   Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Site
US-Ne1   18   18   18   18   18   19   19   19   19   19   19   19
US-Ne2   18   18   18   18   18   19   19   19   19   19   19   19
US-Ne3   18   18   18   18   18   18   19   19   19   19   19   19
US-Var   20   20   21   21   21   21   21   21   20   20   20   20

In [85]:
for var in vars:
    table = results_df[results_df["Variable"] == var].pivot(index="Site", columns="month", values="R2")
    table = table.reindex(month_names, axis=1)
    table = round(table,2)
    #table = table.style.format("{:.2}").background_gradient(cmap='Blues', vmin=0, vmax=0.8)
    #if var == "SIF_ET":
        #table.set_caption(var[:3] + " " + var[4:] + " R²")
    #else:
        #table.set_caption(var+" R²")
    #table.to_latex(var+"_r2.txt", convert_css = True)
    display(table)

month    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
Site
US-Ne1  0.29  0.23  0.54  0.12  0.41  0.19  0.74  0.47  0.15  0.37  0.03  0.01
US-Ne2  0.63  0.01  0.32  0.13  0.52  0.58  0.75  0.10  0.11  0.06  0.01  0.11
US-Ne3  0.22  0.12  0.23  0.00  0.09  0.14  0.46  0.07  0.00  0.01  0.04  0.38
US-Var  0.02  0.11  0.14  0.47  0.73  0.44  0.03  0.03  0.01  0.12  0.20  0.04

month    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
Site
US-Ne1  0.21  0.32  0.01  0.01  0.00  0.26  0.36  0.08  0.16  0.07  0.05  0.10
US-Ne2  0.25  0.10  0.01  0.04  0.06  0.16  0.17  0.17  0.10  0.03  0.01  0.02
US-Ne3  0.03  0.11  0.01  0.00  0.00  0.12  0.02  0.00  0.04  0.20  0.15  0.01
US-Var  0.06  0.26  0.25  0.42  0.85  0.61  0.00  0.12  0.03  0.59  0.77  0.17

month   Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Site
US-Ne1  0.0  0.0  0.0  0.0  0.0 -0.0  0.0  0.0  0.0  0.0  0.0  0.0
US-Ne2  0.0 -0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0  0.0  0.0  0.0
US-Ne3  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0  0.0  0.0  0.0  0.0
US-Var  0.0 -0.0  0.0 -0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0  0.0

month    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
Site
US-Ne1  0.09  0.08  0.11  0.11  0.27  0.24  0.51  0.20  0.13  0.29  0.06  0.00
US-Ne2  0.06  0.04  0.01  0.06  0.29  0.47  0.56  0.02  0.07  0.15  0.04  0.04
US-Ne3  0.09  0.32  0.04  0.04  0.00  0.02  0.17  0.01  0.00  0.00  0.00  0.10
US-Var  0.00  0.18  0.34  0.57  0.78  0.57  0.00  0.11  0.00  0.49  0.14  0.06

month    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
Site
US-Ne1  0.04  0.08  0.08  0.08  0.56  0.18  0.48  0.05  0.11  0.07  0.10  0.01
US-Ne2  0.41  0.00  0.17  0.18  0.55  0.73  0.62  0.00  0.13  0.07  0.01  0.00
US-Ne3  0.02  0.05  0.17  0.01  0.14  0.36  0.36  0.08  0.03  0.00  0.25  0.12
US-Var  0.08  0.01  0.01  0.24  0.49  0.39  0.01  0.00  0.18  0.02  0.03  0.03

month    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
Site
US-Ne1  0.02  0.34  0.56  0.13  0.37  0.07  0.28  0.49  0.16  0.11  0.00  0.02
US-Ne2  0.10  0.00  0.11  0.04  0.40  0.54  0.62  0.50  0.06  0.01  0.03  0.01
US-Ne3  0.04  0.00  0.07  0.02  0.06  0.07  0.33  0.16  0.04  0.06  0.00  0.21
US-Var  0.18  0.07  0.17  0.48  0.69  0.33  0.00  0.00  0.01  0.13  0.54  0.01

month    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
Site
US-Ne1  0.00  0.27  0.03  0.01  0.25  0.19  0.64  0.32  0.12  0.40  0.02  0.13
US-Ne2  0.05  0.05  0.11  0.00  0.46  0.52  0.66  0.09  0.04  0.10  0.00  0.02
US-Ne3  0.00  0.01  0.00  0.10  0.34  0.15  0.33  0.10  0.01  0.03  0.04  0.06
US-Var  0.18  0.45  0.34  0.60  0.59  0.13  0.04  0.05  0.00  0.02  0.46  0.02

month    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
Site
US-Ne1  0.18  0.33  0.54  0.18  0.35  0.08  0.55  0.01  0.09  0.03  0.01  0.02
US-Ne2  0.43  0.02  0.52  0.00  0.61  0.43  0.39  0.00  0.03  0.02  0.02  0.07
US-Ne3  0.21  0.05  0.34  0.01  0.32  0.18  0.31  0.00  0.00  0.02  0.16  0.17
US-Var  0.18  0.23  0.54  0.02  0.52  0.84  0.28  0.15  0.13  0.32  0.50  0.00

month    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
Site
US-Ne1  0.10  0.11  0.04  0.33  0.53  0.14  0.60  0.29  0.13  0.34  0.12  0.13
US-Ne2  0.18  0.24  0.01  0.62  0.65  0.41  0.56  0.08  0.09  0.38  0.37  0.42
US-Ne3  0.29  0.07  0.00  0.44  0.62  0.16  0.24  0.01  0.12  0.48  0.40  0.27

In [64]:
for var in vars:
    table = results_df[results_df["Variable"] == var].pivot(index="Site", columns="month", values="RMSE")
    table = table.reindex(month_names, axis=1)
    table = table.style.format("{:.1f}").background_gradient(cmap='Reds', vmin=0, vmax=50)
    if var == "SIF_ET":
        table.set_caption(var[:3] + " RMSE")
    else:
        table.set_caption(var+" RMSE")
    table.to_latex(var+"_RMSE.txt", convert_css = True)
    display(table)

In [65]:
for var in vars:
    table = results_df[results_df["Variable"] == var].pivot(index="Site", columns="month", values="MAE")
    table = table.reindex(month_names, axis=1)
    table = table.style.format("{:.1f}").background_gradient(cmap='Reds', vmin=0, vmax=50)
    if var == "SIF_ET":
        table.set_caption(var[:3] + " MAE")
    else:
        table.set_caption(var+" MAE")
    table.to_latex(var+"_MAE.txt", convert_css = True)
    display(table)

In [66]:
for var in vars:
    table = results_df[results_df["Variable"] == var].pivot(index="Site", columns="month", values="MBE")
    table = table.reindex(month_names, axis=1)
    table = table.style.format("{:.1f}").background_gradient(cmap='seismic', vmin=-45, vmax=45)
    #table = table.style.format("{:.3f}").background_gradient(cmap='seismic', vmin=-45, vmax=45)
    if var == "SIF_ET":
        table.set_caption(var[:3] + " MBE")
    else:
        table.set_caption(var+" MBE")
    table.to_latex(var+"_MBE.txt", convert_css = True)
    display(table)

In [4]:
fp = ("US-Ne1", "US-Ne2", "US-Ne3", "US-Var")
season_names = ('DJF', 'MAM', 'JJA', 'SON')

comp_vars = ("SIF_ET", "Ensemble", "geeSEBAL", "PT-JPL", "SSEBop", "SIMS", "eeMETRIC", "DisALEXI", "Climatology")
season_results = []
month_occ = []
for fn in fp: 
    df = pd.read_csv(fn+"_clim.csv", delimiter = ',', parse_dates=["Date"])
    df["Date"] = pd.to_datetime(df["Date"])
    df.set_index("Date", inplace=True)
    season_filters = {
    "All Months": df,
    "DJF": df[df.index.month.isin([12, 1, 2])],
    "MAM": df[df.index.month.isin([3, 4, 5])],
    "JJA": df[df.index.month.isin([6, 7, 8])],
    "SON": df[df.index.month.isin([9, 10, 11])],
        }
    season_names = list(season_filters.keys())
    for i, name in enumerate(season_names):
        season_df = season_filters[name]
        for var in comp_vars:
            subset = season_df[["observed_ET", var]].dropna()
            if subset.empty:
                continue

            y = subset[var].values.reshape(-1, 1)
            obs = subset["observed_ET"].values

            model = LinearRegression().fit(y, obs)
            y_pred = model.predict(y)
            r2 = r2_score(obs, y_pred)

            y = y.reshape(-1, )
            y_pred = y_pred.reshape(-1, )

            RMSE = np.sqrt(mean_squared_error(obs, y))
            MAE = mean_absolute_error(obs, y)
            MBE = (sum(y-obs))/len(obs)

            SRMSE = RMSE/(np.std(obs))

            season_results.append({
                "Site": fn,
                "season": name,
                "Variable": var,
                "R2": round(r2, 3),
                "RMSE": round(RMSE, 3),
                "SRMSE": round(SRMSE, 3),
                "MAE": round(MAE,3),
                "MBE": MBE
                })
            

vars = ["Ensemble", "SIF_ET", "Climatology",'eeMETRIC', 'geeSEBAL', 'DisALEXI', 'SSEBop', 'PT-JPL', 'SIMS']
season_names = ["DJF", "MAM", "JJA", "SON"]
season_df = pd.DataFrame(season_results)
display(season_df)
#results_df.to_csv("loc2.csv")
#display(results_df.describe())

       Site      season     Variable     R2    RMSE  SRMSE     MAE        MBE
0    US-Ne1  All Months       SIF_ET  0.878  31.130  0.501  21.373 -11.272479
1    US-Ne1  All Months     Ensemble  0.923  19.546  0.312  15.142  -8.868181
2    US-Ne1  All Months     geeSEBAL  0.869  25.734  0.411  19.131 -12.122861
3    US-Ne1  All Months       PT-JPL  0.893  23.851  0.381  16.917  -9.878526
4    US-Ne1  All Months       SSEBop  0.880  24.971  0.398  19.821  -9.987885
..      ...         ...          ...    ...     ...    ...     ...        ...
170  US-Var         SON       PT-JPL  0.251  24.864  4.893  23.573  23.572522
171  US-Var         SON       SSEBop  0.050  16.136  3.175  11.453   8.609256
172  US-Var         SON     eeMETRIC  0.011  13.362  2.630  10.510   9.527624
173  US-Var         SON     DisALEXI  0.008  13.267  2.611   9.163   6.590889
174  US-Var         SON  Climatology  0.461   3.690  0.734   2.775  -0.000039

[175 rows x 8 columns]

In [5]:
columns = ("R2","RMSE","MAE", "MBE", "SRMSE")
dropped = ("season", "Variable")
for var in vars:
    table = season_df[season_df["Variable"] == var]
    table = table[table["season"]== "All Months"]
    table = table.drop("season", axis = 1)
    table = table.drop("Variable", axis = 1)
    table = table.set_index("Site")
    table = table.reindex(columns, axis=1)
    table = table.style.format({
        "R2": "{:.2f}",
        "RMSE": "{:.1f}",
        "MAE": "{:.1f}",
        "MBE":"{:.1f}"
    })
    if var == "SIF_ET":
        table.set_caption(var[:3] + " " + var[4:] + " All months Stats")
    else:
        table.set_caption(var+" All months stats")
    #table.to_latex(var+"_all_stats.txt", convert_css = True)
    display(table)

In [8]:
for var in vars:
    table = season_df[season_df["Variable"] == var].pivot(index="Site", columns="season", values="SRMSE")
    table = table.reindex(season_names, axis=1)
    table = table.style.format("{:.1f}").background_gradient(cmap='Reds', vmin= 0, vmax=5)
    if var == "SIF_ET":
        table.set_caption(var[:3] + " " + var[4:] + " MBE")
    else:
        table.set_caption(var+" MBE")
    #table.to_latex(var+"_season_MBE.txt", convert_css = True)
    display(table)

In [68]:
for var in vars:
    table = season_df[season_df["Variable"] == var].pivot(index="Site", columns="season", values="MBE")
    table = table.reindex(season_names, axis=1)
    table = table.style.format("{:.1f}").background_gradient(cmap='seismic', vmin= -35, vmax=35)
    if var == "SIF_ET":
        table.set_caption(var[:3] + " " + var[4:] + " MBE")
    else:
        table.set_caption(var+" MBE")
    table.to_latex(var+"_season_MBE.txt", convert_css = True)
    display(table)

In [70]:
for var in vars:
    table = season_df[season_df["Variable"] == var].pivot(index="Site", columns="season", values="MAE")
    table = table.reindex(season_names, axis=1)
    table = table.style.format("{:.1f}").background_gradient(cmap='Reds', vmin=0, vmax=45)
    if var == "SIF_ET":
        table.set_caption(var[:3] + " " + var[4:] + " MAE")
    else:
        table.set_caption(var+" MAE")
    table.to_latex(var+"_season_MAE.txt", convert_css = True)
    display(table)